# Site settings
title: Let it shine!
# the subpath baseurl must be to be publish & working in production under letitshine.ch
# if you want to preview the website under username.github.io/letitshine, you have to change baseurl to /letitshine
baseurl: ""
url: "" # the base hostname & protocol for your site
email: "masha@letitshine.ch"
description: Professionnels du home organizing, architecture d'intérieur et décoration à Lausanne, Suisse. Rénovation, rangement et relooking pour appartements, maisons ou bureaux.

# Build settings
markdown: kramdown
exclude: [node_modules, gulp-config.json, Gulpfile.js, package.json, webpack-config.js, package-lock.json, README.md]