# Site settings
title: Let is Shine
# the subpath baseurl must be to be publish & working in production under letitshine.ch
# if you want to preview the website under username.github.io/letitshine, you have to change baseurl to /letitshine
baseurl: "/letitshine"
url: "" # the base hostname & protocol for your site
email: ""

# Build settings
markdown: kramdown
exclude: [node_modules, gulp-config.json, Gulpfile.js, package.json, webpack-config.js, package-lock.json, README.md]